### ISSUE TITLE
Platform dependance of code

### ISSUE THREAD

**Issue by TanmayAmbadkar** [aashutoshrathi/Testcase-Generator#113]
**Actual Behaviour**

The program does not compile C and C++ codes for windows

**Expected Behaviour**

It should be platform independent

**Steps to reproduce it**

Before execution, check the platform being used, and then run accordingly

**Screenshots of the issue** (if required)

**Would you like to work on the issue?**
I would like to work on this issue

**Comment by aashutoshrathi** [comment]
Sure. Fire a PR.

**Comment by TanmayAmbadkar** [comment]
Solved, please check

**Comment by aashutoshrathi** [comment]
Fixed.
