### ISSUE TITLE
LANG Import Error

### ISSUE THREAD

**Issue by duttanaman1** [aashutoshrathi/Testcase-Generator#155]
from lang_compiler import LANGS
ImportError: cannot import name 'LANGS' from 'lang_compiler'

**Screenshots of the issue** (if required)

![Capture](https://user-images.githubusercontent.com/37544286/76208738-44c10080-6226-11ea-985e-84b145581a68.PNG)
![image](https://user-images.githubusercontent.com/37544286/76208747-4985b480-6226-11ea-93db-927796056205.png)

**Comment by aashutoshrathi** [comment]
Hi, Please use the master branch for this now. The dev branch is under development.
Simply do:
```
git checkout master
```
Hope this helps 😄

cc: @thepushkarp and I will soon make sure that dev is stable to use.

**Comment by thepushkarp** [comment]
@duttanaman1 The import error can also occur if you're not running the script from the tc_generator directory. Could you just verify if it gives the same error when you're in that directory?
