### ISSUE TITLE
Crash on space separated directory names in path

### ISSUE THREAD

**Issue by thepushkarp** [aashutoshrathi/Testcase-Generator#169]
**Actual Behaviour**

If a directory in the path of the tc_gen file has space, the application crashes.
Considers the part before space as command and the next as argument of that command.

**Expected Behaviour**

Should work for all directories, irrespective of the space in the path

**Steps to reproduce it**

Add Testcase-Generator folder inside a directory that has a space in its name and run the project.

**Would you like to work on the issue?**

Yes, but need some help on how to fix this.

**Comment by thepushkarp** [comment]
@aashutoshrathi I have tried to replace the spaces in the path string with '\ ' but while executing, it interprets as '\\ '.

**Comment by aashutoshrathi** [comment]
So, there is not solution we found till now?

**Comment by thepushkarp** [comment]
Tried using subprocess but don't know how to still make it interpret a space as a character of the string than splitting the string from it.

**Comment by aashutoshrathi** [comment]
I think we can come up with hack.
