### ISSUE TITLE
C++11 Support

### ISSUE THREAD

**Issue by MayukhSobo** [aashutoshrathi/Testcase-Generator#189]
If I add -std=c++11 in lang file, it is giving me error like 

FileNotFoundError: [Errno 2] No such file or directory: 'g++ -std=c++11': 'g++ -std=c++11'

**Comment by thepushkarp** [comment]
Hey @MayukhSobo
Changing Line 22 in `lang_compiler.py` to
```py
'compile': ['g++', f'{CMD}.cpp', '-o', CMD, '-std=c++11']},
```
compiles the program with C++11.

Does this work for you?

**Comment by MayukhSobo** [comment]
Thanks. It did work for me

**Comment by aashutoshrathi** [comment]
Can we add this info to README.md and close this issue?

**Comment by thepushkarp** [comment]
Sure. A FAQ section would be cool as we may have few more points that we can add.
